# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_period1', models.IntegerField()),
                ('time_period2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.IntegerField()),
                ('device_type', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Config')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
                ('timestamp', models.DateField()),
                ('file_type', models.CharField(choices=[('A', 'Audio'), ('P', 'Picture'), ('T', 'Text')], max_length=1)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Device')),
            ],
        ),
    ]
