# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170522_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='uuid',
            field=models.CharField(max_length=16),
        ),
    ]
