# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170528_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='uuid',
            field=models.CharField(max_length=20),
        ),
    ]
