# -*- python -*-
Import('env')

lib = env.StaticLibrary('lib', ['Connection.cpp', 'Manager.cpp', 'Device.cpp', 'Serializer.cpp', 'DbManager.cpp'])

env.BoostTests(Glob('tests/*.cpp'), lib)

p = env.Program('server', ['main.cpp'] ,LIBS=[lib])

Return('p')
